[pytest]
markers =
    smoke: Дымовые тесты для критического функционала
    extended: Полный набор расширенных тестов
    slow: Медленные тесты (например, с доступом к сети)
    function
    session
    regression

testpaths = profile
addopts = -v --strict-markers --cov=src --cov-report=term-missing

